server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         - id: Catalog-service
           uri: lb://CATALOG-SERVICE
           predicates:
               - Path=/api/v1/catalog/**


#For oauth2 server to decode jwt coming from client and validate it using a public key from keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/Pos-system-realm

#For client to request for jwt token
      client:
        registration:
          keycloak:
            client-id: Pos-system-auth
            client-secret: eoDCZYdXolTVPALLPj1hJixIQSxFwlUs
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: https://oauth.pstmn.io/v1/callback
        provider:
          keycloak:
            issuer-uri: http://localhost:8280/realms/Pos-system-realm
            token-endpoint: http://localhost:8280/realms/Pos-system-realm/protocol/openid-connect/token
            authorization-endpoint: http://localhost:8280/realms/Pos-system-realm/protocol/openid-connect/auth



